/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoria da tarefa
 */
export type UpdateTaskDtoCategory = typeof UpdateTaskDtoCategory[keyof typeof UpdateTaskDtoCategory];


export const UpdateTaskDtoCategory = {
  GENERAL: 'GENERAL',
  WORK: 'WORK',
  STUDY: 'STUDY',
  PERSONAL: 'PERSONAL',
  HEALTH: 'HEALTH',
  FINANCE: 'FINANCE',
} as const;
